import {Config} from './interfaces';

export const config: Config = {
  KEYCLOAK_URL: window.KEYCLOAK_URL,
  KEYCLOAK_REALM: window.KEYCLOAK_REALM,
  KEYCLOAK_CLIENT_ID: window.KEYCLOAK_CLIENT_ID,
  KEYCLOAK_REDIRECT_URI: window.KEYCLOAK_REDIRECT_URI,
  GRAPHQL_URI: window.GRAPHQL_URI,
  REST_URI: window.REST_URI,
  OPEN_FORMS_BASE_URL: window.OPEN_FORMS_BASE_URL,
  OPEN_FORMS_FORM_ID: window.OPEN_FORMS_FORM_ID,
  OPEN_FORMS_ENTRY_ENV: window.OPEN_FORMS_ENTRY_ENV,
  OPEN_FORMS_SDK_URL: window.OPEN_FORMS_SDK_URL,
  OPEN_FORMS_STYLES_URL: window.OPEN_FORMS_STYLES_URL,
  SHOW_INHABITANT_AMOUNT: window.SHOW_INHABITANT_AMOUNT,
  ADDRESS_RESEARCH_URL: window.ADDRESS_RESEARCH_URL,
};
