import {Config} from './interfaces';

export const config: Config = {
  KEYCLOAK_URL: window.KEYCLOAK_URL,
  KEYCLOAK_REALM: window.KEYCLOAK_REALM,
  KEYCLOAK_CLIENT_ID: window.KEYCLOAK_CLIENT_ID,
  KEYCLOAK_REDIRECT_URI: window.KEYCLOAK_REDIRECT_URI,
  GRAPHQL_URI: window.GRAPHQL_URI,
  SHOW_THEME_SWITCHER: window.SHOW_THEME_SWITCHER,
  DEFAULT_THEME_CLASS: window.DEFAULT_THEME_CLASS,
};
