name: "Deploy to AKS"
description: "Deploys the app with Helm to AKS"

inputs:
  credentials:
    required: true
    description: "The credentials used to login to AKS"
  resource-group:
    required: true
    description: "The resource-group in Azure where the cluster is located"
  cluster-name:
    required: true
    description: "The cluster-name in Azure where the cluster is located"
  repo:
    required: false
    description: "The url of the helm repo"
    default: https://gemeente-denhaag.github.io/helm-charts
  chart:
    required: false
    description: "The name of the helm-chart to use"
    default: generic
  release-name:
    required: true
    description: "The name of the release used by Helm"
  values-file:
    required: true
    description: "The location and name of the values file used for Helm"
  namespace:
    required: true
    description: "The namespace of the AKS cluster to deploy to"
  full-image-url:
    required: true
    description: "The url of the image to deploy to AKS, ie: 'test.cr.url/repo-name:imagetag'"
  extra-params:
    required: false
    description: "Extra params allows you to set extra parameters for the helm deployment, ie: '--set image.fullImage=cr-url/repo-name:imagetag --set name=my-app'"

runs:
  using: "composite"
  steps:
    - name: 'Login to aks and set context'
      uses: azure/aks-set-context@v1
      with:
        creds: '${{ inputs.credentials }}'
        resource-group: '${{ inputs.resource-group }}'
        cluster-name: '${{ inputs.cluster-name }}'
      
    - name: 'Deploy to AKS'
      shell: bash
      run: >
        helm upgrade --install --wait --atomic
        --repo ${{ inputs.repo }}
        ${{ inputs.release-name }}
        ${{ inputs.chart }}
        -f ${{ inputs.values-file }}
        -n ${{ inputs.namespace }}
        --set image.fullImage=${{ inputs.full-image-url }}
        ${{ inputs.extra-params }}