## Configure the ingress resource that allows you to access the
## app installation. Set up the URL
## ref: http://kubernetes.io/docs/user-guide/ingress/
##
ingress:

  ## When the ingress is enabled, a host pointing to this will be created
  ##
  hostname: klantportaal-zgw.acc.denhaag.nl

  ## Specify a tls secret which already exists. tls must be set to true
  ##
  existingTlsSecret: zgw-tls-secret

## Autoscaling configuration
##
autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 10
  # targetCPU: 50
  # targetMemory: 50

## An array to add env vars
## For example:
## env:
##  - name: TEST_VAR
##    value: test
##
env:
  - name: KEYCLOAK_CLIENT_ID
    value: klantportaal-cg
  - name: KEYCLOAK_REALM
    value: zgw-publiek
  - name: KEYCLOAK_REDIRECT_URI
    value: https://klantportaal-zgw.acc.denhaag.nl/keycloak/callback
  - name: KEYCLOAK_URL
    value: https://keycloak-zgw.acc.denhaag.nl/auth/
  - name: GRAPHQL_URI
    value: https://klantportaal-zgw.acc.denhaag.nl/graphql
  - name: REST_URI
    value: https://klantportaal-zgw.acc.denhaag.nl/api
  - name: OPEN_FORMS_SDK_URL
    value: https://openformulieren-zgw.acc.denhaag.nl/static/sdk/open-forms-sdk.js
  - name: OPEN_FORMS_BASE_URL
    value: https://openformulieren-zgw.acc.denhaag.nl/api/v1/
  - name: OPEN_FORMS_FORM_ID
    value: bezwaar-maken
  - name: OPEN_FORMS_ENTRY_ENV
    value: docker
  - name: OPEN_FORMS_STYLES_URL
    value: https://openformulieren-zgw.acc.denhaag.nl/static/sdk/open-forms-sdk.css