name: Build and push image and deploy to aks

on:
  push:
    branches:
      - 'feature/**'
      - master
  pull_request:
    branches:
      - master

env:
  PUSH_AND_DEPLOY: ${{ github.event_name != 'pull_request' && github.ref_name == 'master' }}
  CR_REPO: zgw/klantportaal

jobs:
  build:
    runs-on: ubuntu-latest

    outputs:
      tagToDeploy: ${{ steps.prep.outputs.DOCKERTAG }}

    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@main

      - name: 'Generate unique docker tag to deploy with Helm'
        id: prep
        run: |
            branch=${GITHUB_REF##*/}
            sha=${GITHUB_SHA::8}
            ts=$(date +%s)
            echo "::set-output name=DOCKERTAG::${branch}-${sha}-${ts}"

      - name: 'Docker meta'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.CR_REPO }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=ref,event=tag
            type=sha
            ${{ steps.prep.outputs.DOCKERTAG }}

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v1

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@master

      - name: 'Login to acr'
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: 'Set cache_to env'
        if: env.PUSH_AND_DEPLOY == 'true'
        run: echo "cache_to=type=gha,mode=max" >> $GITHUB_ENV

      - name: 'Build and push deps image'
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-unpriv
          target: deps
          push: ${{ env.PUSH_AND_DEPLOY }}
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.CR_REPO }}:deps
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: ${{ env.cache_to }}

      - name: 'Build and push deps image'
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-unpriv
          target: build
          push: ${{ env.PUSH_AND_DEPLOY }}
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.CR_REPO }}:build
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: ${{ env.cache_to }}
      
      - name: 'Run test image'
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-unpriv
          target: test
          push: false
          tags: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.CR_REPO }}:test
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: ${{ env.cache_to }}

      - name: 'Build and push release image'
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile-unpriv
          push: ${{ env.PUSH_AND_DEPLOY }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: ${{ env.cache_to }}

  deploy-to-test:
    # if: github.ref_name == 'master' && github.event_name != 'pull_request'
    if: github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    needs: build
    environment: test

    steps:
      - name: 'Checkout repo'
        uses: actions/checkout@main

      - name: 'Deploy to AKS'
        uses: Gemeente-DenHaag/custom-actions/deploy-to-aks@main
        with:
          credentials: '${{ secrets.AZURE_CREDENTIALS }}'
          resource-group: '${{ secrets.AKS_RG_TEST_ACC }}'
          cluster-name: '${{ secrets.AKS_CL_NAME_TEST_ACC }}'
          release-name: klantportaal
          values-files: infra/values.yaml,infra/values-test.yaml
          namespace: dhonline-test
          full-image-url: ${{ secrets.ACR_LOGIN_SERVER }}/${{ env.CR_REPO }}:${{ needs.build.outputs.tagToDeploy }}

  publish-npm:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref_name == 'master'

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v2
        with:
          node-version: "14.x"

      - name: lerna bootstrap
        run: |
          npm install -g yarn
          npm install -g lerna
          yarn run bootstrap

      - name: build library
        run: yarn run build

      - name: lerna version
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GIT_AUTHOR_EMAIL: ${{ secrets.GIT_AUTHOR_EMAIL }}
          GIT_AUTHOR_NAME: "Municipality of The Hague"
          GIT_COMMITTER_EMAIL: ${{ secrets.GIT_COMMITTER_EMAIL }}
          GIT_COMMITTER_NAME: "Municipality of The Hague"
        run: |
          git push --set-upstream origin HEAD
          yarn run release -- --yes
      
      - name: lerna publish
        env:
          NPM_ACCESS_TOKEN: ${{ secrets.NPM_ACCESS_TOKEN }}
        run: |
          npm config set "//registry.npmjs.org/:_authToken" "${NPM_ACCESS_TOKEN}"
          npm config set access public
          npm run publish -- --no-verify-access --yes
          npm config delete "//registry.npmjs.org/:_authToken"
