name: Build and push image and deploy to aks

on:
  push:
    branches:
      - 'feature/**'
      - master
  pull_request:
    branches:
      - master

env:
  PUSH_AND_DEPLOY: ${{ github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}

jobs:
  build:
    runs-on: ubuntu-latest
      
    steps:
      - name: 'Check build and deploy var'
        run: echo Check variable $PUSH_AND_DEPLOY

      - name: 'Checkout repo'
        uses: actions/checkout@main

      - name: 'Docker meta'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.ACR_LOGIN_SERVER }}/zgw/klantportaal
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-

      - name: 'Set up QEMU'
        uses: docker/setup-qemu-action@v1

      - name: 'Set up Docker Buildx'
        uses: docker/setup-buildx-action@v1

      - name: 'Login to acr'
        uses: docker/login-action@v1
        with:
          registry: ${{ secrets.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # - name: 'Build and push image'
      #   uses: docker/build-push-action@v2
      #   with:
      #     push: ${{ env.PUSH_AND_DEPLOY }}
      #     tags: ${{ steps.meta.outputs.tags }}
      #     labels: ${{ steps.meta.outputs.labels }}
      #     cache-from: type=gha
      #     cache-to: type=gha,mode=max

  deploy-to-test:
    runs-on: ubuntu-latest
    needs: build
    if: env.PUSH_AND_DEPLOY == 'true'
    steps:
      - name: 'Docker meta'
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ secrets.ACR_LOGIN_SERVER }}/zgw/klantportaal
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-

      - name: 'Checkout zgw kubernetes repo'
        if: env.PUSH_AND_DEPLOY == 'true'
        uses: actions/checkout@main
        with:
          repository: Gemeente-DenHaag/zgw-kubernetes
          path: zgw-kubernetes
          token: ${{ secrets.ZGW_REPO_PAT }}

      - name : 'Login to aks and set context'
        if: env.PUSH_AND_DEPLOY == 'true'
        uses: azure/aks-set-context@v1
        with:
            creds: '${{ secrets.AZURE_CREDENTIALS }}'
            resource-group: '${{ secrets.AKS_RG_TEST_ACC }}'
            cluster-name: '${{ secrets.AKS_CL_NAME_TEST_ACC }}'
        id: login

      - name: 'Deploy to aks'
        if: env.PUSH_AND_DEPLOY == 'true'
        uses: Azure/k8s-deploy@v1.4
        with:
          namespace: 'dhonline-staging'
          manifests: |
              zgw-kubernetes/klantportaal/test/configmap.yml
              zgw-kubernetes/klantportaal/test/ingress.yml
              zgw-kubernetes/klantportaal/service.yml
              zgw-kubernetes/klantportaal/deployment.yml
          images: '${{ steps.meta.outputs.tags }}'